[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "CUDA runtime for CubeCL"
edition.workspace = true
keywords = ["gpu", "cuda"]
license.workspace = true
name = "cubecl-cuda"
readme.workspace = true
repository = "https://github.com/tracel-ai/cubecl/tree/main/crates/cubecl-cuda"
version.workspace = true

[features]
default = [
  "cubecl-runtime/default",
  "cubecl-common/default",
  "cubecl-core/default",
]
std = ["cubecl-runtime/std", "cubecl-common/std", "cubecl-core/std"]

[dependencies]
cubecl-runtime = { path = "../cubecl-runtime", version = "0.1.1", default-features = false, features = [
  "channel-mutex",
] }
cubecl-common = { path = "../cubecl-common", version = "0.1.1" }
cubecl-core = { path = "../cubecl-core", version = "0.1.1" }

half = { workspace = true }
bytemuck = { workspace = true }
cudarc = { version = "=0.11.5", features = ["cuda-12030"] }

log = { workspace = true }
derive-new = { workspace = true }

[dev-dependencies]
cubecl-core = { path = "../cubecl-core", version = "0.1.1", features = [
  "export_tests",
] }
cubecl-linalg = { path = "../cubecl-linalg", version = "0.1.1", features = [
  "export_tests",
] }
